-- ============================================================
-- «Kassa Nazorati» — boshlang'ich sxema (TZ v1.0, 9-bo'lim)
-- Izoh: TZ 6-bo'limdagi KUN_SOF formulasiga muvofiq days jadvaliga
-- o'tkazma ustunlari (kirim_*/chiqim_*) qo'shildi.
-- ============================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id   BIGINT NOT NULL UNIQUE,
    full_name     VARCHAR(120) NOT NULL,
    phone         VARCHAR(32),
    role          VARCHAR(20) NOT NULL,          -- KASSIR | BUXGALTER | SUPERADMIN
    kassa_id      BIGINT,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE kassa (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(120) NOT NULL,
    moysklad_store_id  VARCHAR(64),              -- MoySklad savdo nuqtasi ID (mapping)
    active             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE operations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(20) NOT NULL,        -- PRIXOD|VOZVRAT|RASXOD|OTKAZMA|TOPSHIRIQ|KORREKTIROVKA|BOSHLANGICH
    money_type      VARCHAR(10) NOT NULL,        -- NAQD|KLIK|TERMINAL
    amount          BIGINT NOT NULL CHECK (amount > 0),
    from_owner_type VARCHAR(15),
    from_owner_id   BIGINT,
    to_owner_type   VARCHAR(15),
    to_owner_id     BIGINT,
    status          VARCHAR(15) NOT NULL,        -- KUTILMOQDA|YOLDA|TASDIQLANGAN|RAD_ETILGAN|BEKOR
    category_id     BIGINT,
    transfer_kind   VARCHAR(20),                 -- ODDIY|QARZ_BERISH|QARZ_QAYTARISH
    debt_id         BIGINT,
    submission_id   BIGINT,
    comment         VARCHAR(500),
    reject_reason   VARCHAR(500),
    op_date         DATE NOT NULL,
    moysklad_id     VARCHAR(64) UNIQUE,
    created_by      BIGINT,
    decided_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at      TIMESTAMPTZ
);
CREATE INDEX idx_operations_status  ON operations(status);
CREATE INDEX idx_operations_op_date ON operations(op_date);
CREATE INDEX idx_operations_from    ON operations(from_owner_type, from_owner_id);
CREATE INDEX idx_operations_to      ON operations(to_owner_type, to_owner_id);

-- Kesh-balanslar: har operatsiya bilan bitta DB-tranzaksiyada yangilanadi.
-- Haqiqiy manba — operations jurnali (ledger).
CREATE TABLE balances (
    owner_type  VARCHAR(15) NOT NULL,            -- KASSA | BUXGALTERIYA
    owner_id    BIGINT NOT NULL,                 -- BUXGALTERIYA uchun doim 1
    money_type  VARCHAR(10) NOT NULL,
    amount      BIGINT NOT NULL DEFAULT 0,
    reserved    BIGINT NOT NULL DEFAULT 0,       -- kutilayotgan chiqimlar (rezerv)
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (owner_type, owner_id, money_type)
);

CREATE TABLE days (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kassa_id         BIGINT NOT NULL REFERENCES kassa(id),
    date             DATE NOT NULL,
    prixod_naqd      BIGINT NOT NULL DEFAULT 0,
    prixod_klik      BIGINT NOT NULL DEFAULT 0,
    prixod_terminal  BIGINT NOT NULL DEFAULT 0,
    vozvrat_naqd     BIGINT NOT NULL DEFAULT 0,
    vozvrat_klik     BIGINT NOT NULL DEFAULT 0,
    rasxod_naqd      BIGINT NOT NULL DEFAULT 0,
    rasxod_klik      BIGINT NOT NULL DEFAULT 0,
    kirim_naqd       BIGINT NOT NULL DEFAULT 0,  -- qabul qilingan kirim o'tkazmalar
    kirim_klik       BIGINT NOT NULL DEFAULT 0,
    chiqim_naqd      BIGINT NOT NULL DEFAULT 0,  -- yuborilgan (qabul qilingan) chiqim o'tkazmalar
    chiqim_klik      BIGINT NOT NULL DEFAULT 0,
    covered_naqd     BIGINT NOT NULL DEFAULT 0,  -- buxgalteriya qabul qilgan qism
    covered_klik     BIGINT NOT NULL DEFAULT 0,
    status           VARCHAR(20) NOT NULL DEFAULT 'OCHIQ',
    UNIQUE (kassa_id, date)
);
CREATE INDEX idx_days_kassa_status ON days(kassa_id, status);

CREATE TABLE submissions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kassa_id       BIGINT NOT NULL REFERENCES kassa(id),
    naqd           BIGINT NOT NULL DEFAULT 0,
    klik           BIGINT NOT NULL DEFAULT 0,
    accepted_naqd  BIGINT,
    accepted_klik  BIGINT,
    status         VARCHAR(20) NOT NULL,         -- KUTILMOQDA|QABUL|QISMAN_QABUL|RAD
    submitted_by   BIGINT NOT NULL,
    decided_by     BIGINT,
    comment        VARCHAR(500),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at     TIMESTAMPTZ
);

CREATE TABLE submission_days (
    submission_id BIGINT NOT NULL REFERENCES submissions(id),
    day_id        BIGINT NOT NULL REFERENCES days(id),
    PRIMARY KEY (submission_id, day_id)
);

CREATE TABLE debts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_type   VARCHAR(15) NOT NULL,
    debtor_id     BIGINT NOT NULL,
    creditor_type VARCHAR(15) NOT NULL,
    creditor_id   BIGINT NOT NULL,
    money_type    VARCHAR(10) NOT NULL,
    amount        BIGINT NOT NULL,
    repaid        BIGINT NOT NULL DEFAULT 0,
    status        VARCHAR(15) NOT NULL DEFAULT 'OCHIQ',
    reason        VARCHAR(500),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at     TIMESTAMPTZ
);

CREATE TABLE categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(120) NOT NULL,
    active  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    action     VARCHAR(60) NOT NULL,
    entity     VARCHAR(40),
    entity_id  BIGINT,
    payload    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE settings (
    key   VARCHAR(80) PRIMARY KEY,
    value TEXT
);

-- Standart rasxod kategoriyalari (TZ 7.3)
INSERT INTO categories(name) VALUES
    ('Oylikdan ushlab qolish'),
    ('Shaxsiy ehtiyoj'),
    ('Postavchikka to''lov'),
    ('Ehson'),
    ('Boshqa');
