-- Alohida Click hisoblari: har biri o'z qoldig'iga ega (balances: owner_type=CLICK).
CREATE TABLE click_accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO click_accounts (name) VALUES
    ('Зуфар ака Клик'),
    ('Бобомурод Клик'),
    ('Жасур ака Клик'),
    ('Озод Клик'),
    ('Абдулло ака Клик'),
    ('Камера дукон Клик');
